### ISSUE TITLE
Our paper is not listed under poster presentations in the proceeding

### ISSUE THREAD

**Issue by asarigun** [mlresearch/v198#2]
Dear Editors,

Unfortunately, our paper is not listed under poster presentations in the proceeding. Could you please add our paper (https://openreview.net/forum?id=hZ3b8CskgC) to the LoG Proceedings? I am grateful for your help and interest.

Best Regards,

Ahmet Sarigun

**Comment by lawrennd** [comment]
Thanks for flagging Ahmet. Could you also flag with the proceedings editors? They should then be able to create a pull request to add it.

**Comment by asarigun** [comment]
Thank you so much for your quick response, @lawrennd! I emailed editors about the issue. 

Best,

Ahmet
